### ISSUE TITLE
Set node version for local development env

### ISSUE THREAD

**Issue by noahsw** [league-wins-pool/league-wins-pool#2]
We set the node version in our Dockerfile. We should do the same on our dev machines so we're coding against the same thing. 

One obvious place to set it is the package.json file. We have to see if it supports that.

**Comment by charleskrueger** [comment]
https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

It is pretty straight forward, although I'm not sure how node handles
updating itself based on its package.json file, I'll take a look


––––––––––––––––––––––––––––––––––––––
Charles Krueger
owner  /  developer  /  designer
p 206.310.7873
fiveleft.com

**Comment by noahsw** [comment]
From https://docs.npmjs.com/files/package.json

## engines

You can specify the version of node that your stuff works on:

{ "engines" : { "node" : ">=0.10.3 <0.12" } }
And, like with dependencies, if you don't specify the version (or if you specify "*" as the version), then any version of node will do.

If you specify an "engines" field, then npm will require that "node" be somewhere on that list. If "engines" is omitted, then npm will just assume that it works on node.

You can also use the "engines" field to specify which versions of npm are capable of properly installing your program. For example:

{ "engines" : { "npm" : "~1.0.20" } }
**Note that, unless the user has set the engine-strict config flag, this field is advisory only.**

## engineStrict

NOTE: This feature is deprecated and will be removed in npm 3.0.0.

If you are sure that your module will definitely not run properly on versions of Node/npm other than those specified in the engines object, then you can set "engineStrict": true in your package.json file. This will override the user's engine-strict config setting.

Please do not do this unless you are really very very sure. If your engines object is something overly restrictive, you can quite easily and inadvertently lock yourself into obscurity and prevent your users from updating to new versions of Node. Consider this choice carefully.

**Comment by noahsw** [comment]
From http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html, `npm` will only fire a warning if you run `npm install client` from the `src/webapp` folder. It won't fire a warning when running `npm install` within `src/webapp/client`. Kinda weird.
