### ISSUE TITLE
Consider integrating Facebook's Flow library

### ISSUE THREAD

**Issue by noahsw** [league-wins-pool/league-wins-pool#36]
https://github.com/facebook/flow

It's a static type checker for JS. Helps with compile time warnings.

**Comment by noahsw** [comment]
http://www.keendevelopment.ch/flow-babel-gulp-es6/

**Comment by noahsw** [comment]
https://github.com/facebook/flow/issues/62#issuecomment-113292873

**Comment by noahsw** [comment]
https://github.com/MeteorCommunity/discussions/issues/55

**Comment by jamiter** [comment]
It's already in the ecmascript package: https://github.com/meteor/meteor/blob/devel/packages/ecmascript/README.md#syntax

Search for "flow".
